In [2]:
import numpy as np
import pandas as pd 
import networkx as nx
from graphviz import Digraph
import matplotlib.pyplot as plt

In [3]:
df_alph = pd.read_csv('./soc-sign-bitcoinalpha.csv',header=None)
df_alph

          0     1   2           3
0      7188     1  10  1407470400
1       430     1  10  1376539200
2      3134     1  10  1369713600
3      3026     1  10  1350014400
4      3010     1  10  1347854400
...     ...   ...  ..         ...
24181  7604  7601  10  1364270400
24182  7601  7604  10  1364270400
24183  7604  7602  10  1364270400
24184  7602  7604  10  1364270400
24185  7604  7603 -10  1364270400

[24186 rows x 4 columns]

In [4]:
fairness = {}
for i in range(df_alph.shape[0]):
    fairness[df_alph.loc[i, 0]] = 1

goodness = {}
for i in range(df_alph.shape[0]):
    goodness[df_alph.loc[i, 1]] = 1

In [5]:
def next_goodness(dict):
    for v in dict.keys():
        in_v = 0 #all the predecessors of v
        sum = 0
        for i in range(df_alph.shape[0]):
            if v == df_alph.loc[i, 1]:
                in_v += 1
                sum += fairness[df_alph.loc[i, 0]] * df_alph.loc[i, 2] / 10
        dict[v] = sum / in_v
    return dict

def next_fairness(dict):
    for u in dict.keys():
        out_u = 0
        sum = 0
        for i in range(df_alph.shape[0]):
            if(u == df_alph.loc[i, 0]):
                out_u += 1
                sum += abs(df_alph.loc[i, 2] / 10 - goodness[df_alph.loc[i, 1]])
        dict[u] = 1 - sum / out_u
    return dict 

def judge_goodness(dict):
    next = next_goodness(dict)
    for u, g in dict.items():
        for u_next, g_next in next.items():
            if(u == u_next):
                if(abs(g - g_next) > 0.01):
                    return True
    return False

def judge_fairness(dict):
    next = next_fairness(dict)
    for u, g in dict.items():
        for u_next, g_next in next.items():
            if(u == u_next):
                if(abs(g - g_next) > 0.01):
                    return True
    return False

def FGA(dict_f, dict_g):
    t = 0
    if ((judge_goodness(dict_g)) or judge_fairness(dict_f)):
        t = t + 1
        print(t)
        g = next_goodness(dict_g)
        f = next_fairness(dict_f)
    return f, g

In [7]:
FGA(fairness, goodness)[1]

In [ ]:
FGA(fairness, goodness)[0]